language: r
sudo: false
cache: packages

github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'library(covr);coveralls()'

before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true
