language: r
sudo: false
cache: packages

github_packages: jimhester/covr

after_success:
  - Rscript -e 'library(covr);coveralls()'

on_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change
