# R package
# Test an R package

resources:
  repositories:
    - repository: r-azure-pipelines
      type: github
      name: r-lib/r-azure-pipelines
      endpoint: r-lib

jobs:
  - env:
      GMAILR_APP: $(GMAILR_APP)
      GMAILR_EMAIL: $(GMAILR_EMAIL)
      GMAILR_PASSWORD: $(GMAILR_PASSWORD)
  - template: azure-tidyverse.yml@r-azure-pipelines
