variables:
  GMAILR_APP: $(GMAILR_APP_SECRET)
  GMAILR_EMAIL: $(GMAILR_EMAIL_SECRET)
  GMAILR_PASSWORD: $(GMAILR_PASSWORD_SECRET)

resources:
  repositories:
    - repository: r-azure-pipelines
      type: github
      name: r-lib/r-azure-pipelines
      endpoint: r-lib
      ref: refs/heads/test-env

jobs:
  - template: azure-tidyverse.yml@r-azure-pipelines
